
USE defaultdb;

START TRANSACTION;
USE defaultdb;
DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS weather_data;
DROP TABLE IF EXISTS locations;

CREATE TABLE locations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  latitude DECIMAL(10,6) NULL,
  longitude DECIMAL(10,6) NULL,
  altitude DECIMAL(10,2) NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE weather_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  locationId INT NOT NULL,
  date DATE NOT NULL,
  hour INT NOT NULL,
  tempC FLOAT NULL,
  `condition` VARCHAR(64) NULL,
  humidity INT NULL,
  windKph FLOAT NULL,
  uv FLOAT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_weather_location FOREIGN KEY (locationId) REFERENCES locations(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_location_date_hour UNIQUE (locationId, date, hour)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE favorites (
  id INT AUTO_INCREMENT PRIMARY KEY,
  locationId INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_fav_location FOREIGN KEY (locationId) REFERENCES locations(id)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO locations (name, latitude, longitude, altitude)
VALUES
  ('Mumbai', 19.076000, 72.877700, 14.00),
  ('Bengaluru', 12.971600, 77.594600, 920.00);

-- Insert 24 hours of weather data for Mumbai
INSERT INTO weather_data (locationId, date, hour, tempC, `condition`, humidity, windKph, uv)
SELECT 
  (SELECT id FROM locations WHERE name = 'Mumbai') AS locationId,
  '2025-11-19' AS `date`,
  h.h AS `hour`,
  ROUND(26 + 4 * SIN((h.h - 5) / 24 * 2 * PI()), 1) AS tempC,
  CASE
    WHEN h.h BETWEEN 10 AND 16 THEN 'clear'
    WHEN h.h BETWEEN 6 AND 9 OR h.h BETWEEN 17 AND 19 THEN 'cloudy'
    ELSE 'rain'
  END AS `condition`,
  60 + (h.h % 20) AS humidity,
  10 + (h.h % 12) AS windKph,
  CASE WHEN h.h BETWEEN 6 AND 17 THEN LEAST(8, GREATEST(0, h.h - 6)) ELSE 0 END AS uv
FROM (
  SELECT 0 AS h UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
  UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
  UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
  UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23
) AS h;

-- Insert 24 hours of weather data for Bengaluru
INSERT INTO weather_data (locationId, date, hour, tempC, `condition`, humidity, windKph, uv)
SELECT 
  (SELECT id FROM locations WHERE name = 'Bengaluru') AS locationId,
  '2025-11-19' AS `date`,
  h.h AS `hour`,
  ROUND(23 + 3 * SIN((h.h - 5) / 24 * 2 * PI()), 1) AS tempC,
  CASE
    WHEN h.h BETWEEN 10 AND 16 THEN 'clear'
    WHEN h.h BETWEEN 6 AND 9 OR h.h BETWEEN 17 AND 19 THEN 'cloudy'
    ELSE 'rain'
  END AS `condition`,
  55 + (h.h % 22) AS humidity,
  8 + (h.h % 10) AS windKph,
  CASE WHEN h.h BETWEEN 6 AND 17 THEN LEAST(8, GREATEST(0, h.h - 6)) ELSE 0 END AS uv
FROM (
  SELECT 0 AS h UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
  UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
  UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
  UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23
) AS h;

-- Seed a favorite (Mumbai)
INSERT INTO favorites (locationId)
SELECT id FROM locations WHERE name = 'Mumbai' LIMIT 1;

COMMIT;
